### ISSUE TITLE
get Error after 18 hours login

### ISSUE THREAD

**Issue by ilhamiarie** [cslinmiso/LineAPI4J#14]
Hello @cslinmiso. thanks for the code.
Previously, this app is running normally , but after 18 hours running , I can not log in again . and got an error like this . could there be a solution that can solve the problem.

TalkException(code:INTERNAL_ERROR, reason:null, parameterMap:null)
	at line.thrift.TalkService$getLastOpRevision_result$getLastOpRevision_resultStandardScheme.read(TalkService.java:14103)
	at line.thrift.TalkService$getLastOpRevision_result$getLastOpRevision_resultStandardScheme.read(TalkService.java:1)
	at line.thrift.TalkService$getLastOpRevision_result.read(TalkService.java:14025)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
	at line.thrift.TalkService$Client.recv_getLastOpRevision(TalkService.java:2352)
	at line.thrift.TalkService$Client.getLastOpRevision(TalkService.java:2340)
	at io.cslinmiso.line.api.impl.LineApiImpl.getLastOpRevision(LineApiImpl.java:591)
	at io.cslinmiso.line.model.LineClient.init(LineClient.java:134)
	at io.cslinmiso.line.model.LineClient.<init>(LineClient.java:119)

**Comment by cslinmiso** [comment]
Hi glad you like it.
I had no idea how and why this error happened, I have never try to run it more than an hour. However, you could probably update the connection once a while. Which you could start by renewing auth token few hours a time.
Just give it a try :)
