### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by ghost** [cslinmiso/LineAPI4J#22]
HI
When Clone the latest version and running the main class "io.cslinmiso.LineAPI4J.App", an internal error has occurred.

1. The parameter of loginWithIdentityCredentialFor Certificate is insufficient. 
2. The domain for Polling has changed. 
3. Other reasons.
 I think that are problems.

```
TalkException(code:INTERNAL_ERROR, reason:Internal error, parameterMap:null)
	at line.thrift.TalkService$loginWithIdentityCredentialForCertificate_result$loginWithIdentityCredentialForCertificate_resultStandardScheme.read(TalkService.java:47020)
	at line.thrift.TalkService$loginWithIdentityCredentialForCertificate_result$loginWithIdentityCredentialForCertificate_resultStandardScheme.read(TalkService.java:1)
	at line.thrift.TalkService$loginWithIdentityCredentialForCertificate_result.read(TalkService.java:46936)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
	at line.thrift.TalkService$Client.recv_loginWithIdentityCredentialForCertificate(TalkService.java:3320)
	at line.thrift.TalkService$Client.loginWithIdentityCredentialForCertificate(TalkService.java:3301)
	at io.cslinmiso.line.api.impl.LineApiImpl.login(LineApiImpl.java:238)
	at io.cslinmiso.line.model.LineClient.login(LineClient.java:95)
	at io.cslinmiso.LineAPI4J.App.main(App.java:61)

```

**Comment by ruyaoyao** [comment]
Someone mentioned that it is still possible to login using authToken which can be acquired via QR code. 
It seems to be a way? Though I have not yet try it.

refer  https://github.com/carpedm20/LINE/issues/135
https://github.com/carpedm20/LINE/issues/131

**Comment by ii64** [comment]
I know how the LINE chrome works, loginWithIdentityCredentialForCertificate removed i think cuz the Offical is not use that function >.<)/

and about polling domain, Its still same.

THIS IS NOT THE END.

this the end for that who lazy to re sniff a.k.a. reducing bot maker, i like share, but you must know they are watching us.

**Comment by ruyaoyao** [comment]
@anysz Thank you!
I don't think it's a good idea to share the method here neither.  I guess they will have to figure out how to login by reverse-engineering LINE chrome to it :/

**Comment by ii64** [comment]
Yap, i just found the other function to login with email. Hope you guys found that too, also login qr isnt permanent, the authtoken can be expired.
Going to next step reverse making account with protocol 😀😏

**Comment by supersonictw** [comment]
Well,I know how to fix it.
But I have to protect LINE's Security,I can't answer your question now.
Sorry...

**Comment by Ploiiz** [comment]
@anysz @cslinmiso I don't understand as your discuss on above.
Could you please help to explain step for try to test login.
I'm very serious :(

**Comment by ii64** [comment]
@Ploiiz Right now, the function for login with email on the CURVE is patched. We was figure that out since LINE still updating it with MAC DESKTOP Header. The point is people can login their bot(s) cause someone was share login with qr somewhere. and we like wtf, they might patch login qr too. atleast i got other way to login with email. uploaded but private. got all function on line, i named it cuprum.thrift

**Comment by Ploiiz** [comment]
Could you please help explain for you solution to login as step by step.
Thank you for the greatest advise.

2017-08-08 16:15 GMT+07:00 Anysz101 <notifications@github.com>:
