### ISSUE TITLE
send image file had error.

### ISSUE THREAD

**Issue by winweb** [cslinmiso/LineAPI4J#3]
I coding like this.

          File initialFile = new File("/Users/555/Desktop/image.jpg");
          InputStream targetStream = new FileInputStream(initialFile);
          System.out.println(someoneContact.sendImage(targetStream));

error output:

java.lang.NullPointerException
      at org.apache.thrift.protocol.TCompactProtocol.writeString(TCompactProtocol.java:325)
      at line.thrift.Message$MessageStandardScheme.write(Message.java:1391)
      at line.thrift.Message$MessageStandardScheme.write(Message.java:1)
      at line.thrift.Message.write(Message.java:1068)
      at line.thrift.TalkService$sendMessage_args$sendMessage_argsStandardScheme.write(TalkService.java:28485)
      at line.thrift.TalkService$sendMessage_args$sendMessage_argsStandardScheme.write(TalkService.java:1)
      at line.thrift.TalkService$sendMessage_args.write(TalkService.java:28381)
      at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:63)
      at line.thrift.TalkService$Client.send_sendMessage(TalkService.java:4687)
      at line.thrift.TalkService$Client.sendMessage(TalkService.java:4678)
      at io.cslinmiso.line.api.impl.LineApiImpl.sendMessage(LineApiImpl.java:470)
      at io.cslinmiso.line.model.LineClient.sendMessage(LineClient.java:486)
      at io.cslinmiso.line.model.LineBase.sendImage(LineBase.java:203)
      at io.cslinmiso.LineAPI4J.App.main(App.java:99)

Can you suggest me the this error output ???

**Comment by cslinmiso** [comment]
I will have to look into it while I am free. Thanks.

**Comment by winweb** [comment]
@ruyaoyao Thanks

**Comment by cslinmiso** [comment]
I do find out what the problem is, but the latest problem is that we are not able to log in lol.......

**Comment by Tomas2k** [comment]
I suffer the same problem(NullPointerException) as @winweb when send the images . 
Could you give some direction?
Thanks.

**Comment by cslinmiso** [comment]
Sorry for the late reply.
The problem was the method, sendImage itself. I haven't got the time to fix it.
I will try to fix it around Jan, 2016.

**Comment by cslinmiso** [comment]
@winweb , @Tomas2k .
The sendImage problem has been resolved. Please let me know if there's any problem.
https://goo.gl/u4YYuG

**Comment by winweb** [comment]
@cslinmiso Thanks for your resolved.

**Comment by cslinmiso** [comment]
@winweb Thank you for reporting it.
By the way, if you don't mind, may I know where you from?
