### ISSUE TITLE
read new incoming message.

### ISSUE THREAD

**Issue by menyatukanvisi** [cslinmiso/LineAPI4J#4]
I tried to take incoming messages , use the " longpoll " on LineClient class , but happened " Exception " ..

Sep 09, 2015 6:58:42 PM io.cslinmiso.line.model.LineClient longPoll
SEVERE: null
org.apache.thrift.transport.TTransportException: HTTP Response code: 410
	at org.apache.thrift.transport.THttpClient.flush(THttpClient.java:349)
	at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:65)
	at line.thrift.TalkService$Client.send_fetchOperations(TalkService.java:1413)
	at line.thrift.TalkService$Client.fetchOperations(TalkService.java:1404)
	at io.cslinmiso.line.api.impl.LineApiImpl.fetchOperations(LineApiImpl.java:486)
	at io.cslinmiso.line.model.LineClient.longPoll(LineClient.java:550)
	at io.cslinmiso.line.model.LineClient.longPoll(LineClient.java:530)

Is there any way to fixing this problem?

**Comment by cslinmiso** [comment]
I will have to look into it while I am free. Thanks.

**Comment by cslinmiso** [comment]
duplicated with #8
